baseURL = "https://www.flying-scotts.uk"
languageCode = "en-gb"
title = "The Flying Scotts"
canonifyurls = false
relativeURLs = false
theme = ""
copyright = "2026 The Flying Scotts"
disqusShortname = "flying-scotts"

[pagination]
  pagerSize = 8

[params]
  DateForm = "2 Jan 2006"
  postSummariesFrontPage = 4
  showReadTime = true

[params.author]
  name = "Chris Scott"
  email = "user@example.com"

[[params.social]]
  title = "linkedin"
  url = "https://linkedin.com/in/chrisdjscott"

[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/chrisdjscott"

[[params.social]]
  title = "github"
  url = "https://github.com/chrisdjscott"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "About"
  url = "/about"
  weight = -180

[permalinks]
  posts = "/:year/:1/:2/:title"
